
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multi
  name: multiresource
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 0.5
        memory: 512Mi
  - image: redis
    name: redis
    resources:
      limits:
        cpu: 2
        memory: 1Gi
      requests:
        cpu: 1
        memory: 512Mi
