apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: replicalabel
  name: myreplicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: nginx
        name: nginx
